version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: cardapio_pass
      POSTGRES_USER: cardapio_user
      POSTGRES_DB: cardapio_db
    ports:
      - 5435:5435
    container_name: cardapio
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 4040:4040